### ISSUE TITLE
why to store all the nodes in the index.html.

### ISSUE THREAD

**Issue by veerareddyakkili** [Nhogs/popoto#33]
Why to store all the nodes in index.html and if  i have 1000 nodes, if i store all of them in index.html, size of the file would grow.

**Comment by Popotojs** [comment]
You don't have to store all nodes in index.html, only the schema of the database and only for the node labels and attributes you want to display.
Popoto needs this schema to know which attributes to return when queries are built.

If you look at the [movie example](https://github.com/Nhogs/popoto-examples/tree/master/simple-graph):

The minimum config to provide is the label list with [constraintAttribute](https://github.com/Nhogs/popoto/wiki/Node-configuration#constraint-attribute) and [returnAttributes](https://github.com/Nhogs/popoto/wiki/Node-configuration#return-attributes)

```javascript
    popoto.provider.node.Provider = {
        "Movie": {
            "returnAttributes": ["title"],
            "constraintAttribute": "title"
        },
        "Person": {
            "returnAttributes": ["name"],
            "constraintAttribute": "name"
        }
    };
```
