### ISSUE TITLE
Bolt support?

### ISSUE THREAD

**Issue by debugpoint136** [Nhogs/popoto#35]
Hi,

Keep up the excellent work on this package!
I am super motivated to try it out
I created a sandbox using `https://neo4j.com/sandbox-v2/`
The examples included show how to connect using rest endpoint.
Is bolt supported? For example, can I connect using -
```
server_url: "bolt://54.23.45.67:7687"
server_user: "neo4j"
server_password: "sorts-swims-burglaries"
```

Please let me know. Thanks!!! Appreciate your time

**Comment by Popotojs** [comment]
Sorry BOLT is not yet supported but it is planned to use [Neo4j Javascript driver](https://neo4j.com/docs/api/javascript-driver/current/) internally.

For now you can only use [REST API](https://neo4j.com/docs/rest-docs/current/) through HTTP or HTTPS requests.
Which will be remove in Neo4j 4.0

See details [here](https://github.com/Nhogs/popoto/wiki/Getting-started#define-the-credentials-to-access-the-database) on how to configure the credentials

**Comment by Toparvion** [comment]
This is getting more important as Neo4J 4.0 is already in Release Candidate stage. We've started to use it but unfortunately current Popotojs is not compatible with it. 
We'd really like to become Popotojs fans and we're looking forward for its future releases.

**Comment by ninjakx** [comment]
@Popotojs :

Unable to run simple example:

```
    // Demo Neo4j database settings hosted on GrapheneDb
    popoto.rest.CYPHER_URL = "http://localhost:7474/db/data/transaction/commit";
    popoto.rest.AUTHORIZATION = "Basic " + btoa("neo4j:1234");
    console.log("-->", popoto);
```

Works in browser `enter your credential thing`. but when I provide all the credential in the script it doesn't work.

**Comment by Popotojs** [comment]
Popoto 3.0.0 is now using bolt from Neo4j Javascript driver
https://github.com/Nhogs/popoto/wiki/Getting-started#define-the-neo4j-driver-to-connect-to-the-database
