### ISSUE TITLE
Bug/Feature Directed graph

### ISSUE THREAD

**Issue by anyAiFunc** [Nhogs/popoto#36]
Hello there,

no incoming edges are displayed. Is this intended or will it be implemented?

**Comment by gettingtoknowdata** [comment]
https://github.com/Nhogs/popoto/wiki/Query-configuration 

> popoto.query.USE_RELATION_DIRECTION = false;

may help you

**Comment by Popotojs** [comment]
This is intended by default to avoid the possibility to build inifinite hop by following cycle (a)-[]->(b)-[]->(a)... 
You can activate it in configuration to allow it in graph.

Or define a schema to describe a subset of the relationships to display.

With this configuration example you'll show only two "reverse" relations from Movie nodes (ACTED_IN and DIRECTED) 

```Javascript
popoto.provider.node.Provider = {
    "Movie": {
        "returnAttributes": ["title", "released", "tagline"],
        "constraintAttribute": "title",
        schema: {
            label: 'Movie',
            rel: [
                {
                    label: "ACTED_IN",
                    isReverse: true,
                    target: {
                        label: "Person",
                    }
                },
                {
                    label: "DIRECTED",
                    isReverse: true,
                    target: {
                        label: "Person",
                    }
                },
            ]
        }
    },
    "Person": {
        "returnAttributes": ["name", "born"],
        "constraintAttribute": "name"
    }
};
```
