### ISSUE TITLE
Feature "Clear"

### ISSUE THREAD

**Issue by sthausherr** [Nhogs/popoto#44]
I currently have a use case where I destroy and rebuild the Angular(6) component and Popoto is not reinitialized. But in the dataModel it still holds the nodes and the browser freezes because a new root node wants to attach to it. Therefore the question gives a possibility to empty/clear everything?

**Comment by Popotojs** [comment]
You can use the `reset` function defined in `tools` module: `popoto.tools.reset();`
It is the code used on click on the [reset button](https://github.com/Nhogs/popoto/wiki/Toolbar#reset-graph).

You can also customize the work done in reset, see this [example](https://github.com/Nhogs/popoto-examples/tree/master/reset-customization).

**Comment by sthausherr** [comment]
Hey,
excuse me but reset not help for me. i use this:

dataModel.nodes.length = 0;
dataModel.links.length = 0;

thanks

This ticket can be closed

**Comment by AnjaliSankaran** [comment]
Hi, 
I tried
popoto.tools.reset(); and also 
dataModel.nodes.length = 0;
dataModel.links.length = 0;

when I use,
dataModel.nodes.length = 0;
dataModel.links.length = 0;
the taxonomies data, cypherviewer data are getting duplicated and nodes are not loading on click of taxonomy.
I am using Angular 9.
It will be great if anybody can help :)

Thanks!!
