### ISSUE TITLE
Port popoto for RDF and SPARQL

### ISSUE THREAD

**Issue by xgfd** [Nhogs/popoto#52]
Hi, I'm trying to build a similar query builder for SPARQL and RDF. Do you think it'd be possible to do so based on this greate project? Where would be the best place to start? Many thanks.

**Comment by Popotojs** [comment]
Yes it is possible, but today Popoto is still very linked to Cypher, the graph query is a direct mapping to a Cypher Query. 

To do this I think the changes should be done in [generated queries](https://github.com/Nhogs/popoto/blob/master/src/query/query.js) and [REST connection](https://github.com/Nhogs/popoto/blob/master/src/rest/rest.js)

**Comment by xgfd** [comment]
Thank you. That's very helpful.
