### ISSUE TITLE
Switch node for which results are displayed

### ISSUE THREAD

**Issue by ghost** [Nhogs/popoto#53]
Hi there,
first I want to say thanks for this great project! 

On to the issue: I use the results view to display additional information on the queried results of the root node. However it would be great if users could switch the node that results are queried for dynamically without selecting a new base node type. So for an open query they could simply do something like shift-click on the node they want the results view to shift to.

I tried to add the functionality on my own by modifying the root node of the result query generator, but that led to multiple bugs in the graph functionality.

Do you have any pointers on how to go about implementing this feature?

**Comment by Popotojs** [comment]
Hi, this is a good idea and I'll see if I can add it as a feature!

I did a quick test whithout modifying existing code but by using the ```popoto.graph.getSchema()``` function where I modify a random node and set it as new root and reset the graph with the new model.

See a live example here: https://github.com/Nhogs/popoto-examples/tree/master/change-query-root
