### ISSUE TITLE
Reverse donut

### ISSUE THREAD

**Issue by q1044019** [Nhogs/popoto#54]
Is there a way to show the donut to the relationships that arrive at the node (not just those originating at the node)? That would make it easier to search.

**Comment by Popotojs** [comment]
Duplicate of #36

**Comment by Popotojs** [comment]
Does #36 answers your question?
Would you like additional elements to differentiate the direction of the relationships in donuts?

**Comment by q1044019** [comment]
#36 was what I'm looking for. Thanks.
