### ISSUE TITLE
error while accessing Neo4j server on URL:"..." defined in "rest.CYPHER_URL" property: Bad Request

### ISSUE THREAD

**Issue by gustavoK47** [Nhogs/popoto#56]
Good afternoon, 
I am trying to implement popoto in my project but the console is throwing this error:
"error: error while accessing Neo4j server on URL:"http://localhost:7474/db/data/transaction/commit" defined in "rest.CYPHER_URL" property: Bad Request"

I noticed the the cypher query displayed in the cypher query viewer encloses the column name in single braces (which does not work if I execute the query directly in the browser). I am using Neo4j server version 3.5.0.

**Comment by ninjakx** [comment]
@gustavoK47 : are your able to use popotojs using localhost endpoint? Can you help me with setting neo4j with popotojs locally because nothing works for me :(

**Comment by Popotojs** [comment]
Popoto 3.0.0 is now using bolt from Neo4j Javascript driver
https://github.com/Nhogs/popoto/wiki/Getting-started#define-the-neo4j-driver-to-connect-to-the-database
