### ISSUE TITLE
Add d3-voronoi to examples and documentation

### ISSUE THREAD

**Issue by thlaegler** [Nhogs/popoto#72]
Starting with a simple example in plain HTML+JS (no Node) I ran into this issue:
https://github.com/Nhogs/popoto-examples/issues/17

To fix this I had to add `<script src="https://d3js.org/d3-voronoi.v1.min.js"></script>`.

But this fix/requirement is not mentioned anywhere in the docs or examples.

**Comment by Popotojs** [comment]
Best way to fix this for now is to use older version of D3 (v.5.15.0)
Popoto needs to be updated to latest version but I don't know when it will be done

```js
<script src="https://unpkg.com/d3@5.15.0" charset="utf-8"></script>
```
