### ISSUE TITLE
any way to connect to the neo4j without exposing credentials?

### ISSUE THREAD

**Issue by wspi** [Nhogs/popoto#73]
Hi,

is there a way to connect to the neo4j server, without exposing the credentials? like using another app as a proxy or anything else so the connection to the neo4j becames server side?

thanks

**Comment by Popotojs** [comment]
Hi Popoto is using Neo4j javascript driver now
You can find a discussion on how not to expose the credentials here:
https://community.neo4j.com/t/protect-the-database-login-credentials-when-working-with-javascript/1052/3
