### ISSUE TITLE
Using bolt with popoto.js

### ISSUE THREAD

**Issue by shoaib-jpeg** [Nhogs/popoto#74]
Hi everyone, just wanted to know if popoto js has support for bolt now.  I read that in recent versions of popoto there was no support for bolt.. Reason I'm asking is because I get this error in my console: 
![image](https://user-images.githubusercontent.com/68448600/107501457-68db3f00-6b65-11eb-9191-68e02dfa5c9e.png)
and my config is as such: 
![image](https://user-images.githubusercontent.com/68448600/107501678-b9529c80-6b65-11eb-85f1-9dbbe61a15fa.png)

I don't know if my errors are because of the lack of support or because I haven't configured it properly.  I would really appreciate it if someone can provide any explanation. Thank you in advance.

**Comment by epugh** [comment]
The last commit on this project was in 2019...  I love what this project *could* have been, but it's abandon-ware these days.

**Comment by webstationhq** [comment]
Have you configured your Neo4J instance to use bolt on that port in the config file?

**Comment by Popotojs** [comment]
Popoto 3.0.0 is now using bolt from Neo4j Javascript driver 
https://github.com/Nhogs/popoto/wiki/Getting-started#define-the-neo4j-driver-to-connect-to-the-database
