### ISSUE TITLE
d3-selection

### ISSUE THREAD

**Issue by blamnyc** [Nhogs/popoto#76]
Hello, I'd like to install both Popoto.js and React Flow onto a React project, but Popoto is using an older version of d3-selection (v. 1.4.2) while React Flow is using the latest version (v. 2.0.0).   I'm not really familiar with d3.   Do you think it would be a huge undertaking to update Popoto to use the latest d3 lib collection?

This is the error I'm encountering:

TypeError: exitingData.filter(...).transition is not a function
push../node_modules/popoto/src/graph/node/node.js.node.removeElements

    exitingData.filter(function (d) {
        return d.parent;
    }).transition().duration(300).attr("transform", function (d) {
        return "translate(" + d.parent.x + "," + d.parent.y + ")";
    }).remove();

**Comment by Popotojs** [comment]
Popoto 4.0.0 now uses d3 version 7.6.1, this should fix this issue.
