### ISSUE TITLE
An ability to set (reload) a new scheme in the same browser session

### ISSUE THREAD

**Issue by zkbitcoin** [Nhogs/popoto#81]
hello

using popoto API call: popoto.start(schema_1) with a single scheme without a problem (using popoto npm package in the native react environment)

next I tried do change the scheme (in the same browser session so same neo4j connection) popoto.start(schema_2) during which call browser froze 

one can I guess easily replicate the problem by issuing two calls in succession

popoto.start(schema_1)
popoto.start(schema_2)

---

wondering if there is an API  to reload the scheme which would remove previous graph rendering and load fresh new scheme in its place

if one is within the same scheme one can change root (one particular example demonstrates this nicely) but I need to completely load brand new scheme in place of the previous (without obviously complete browser refresh)

**Comment by zkbitcoin** [comment]
update: this seemed to work 

popoto.start("Entity_1");
popoto.graph.mainLabel = "Entity_2"
popoto.tools.reset();

**Comment by Popotojs** [comment]
This is the right way to load another schema, but instead of "Entitity_2" you can use a schema.
```popoto.graph.mainLabel = schema_2``` 
You can have a look at this [save example](https://nhogs.github.io/popoto-examples/save/index.html) where schemas are loaded and saved in same session.
