### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by zhangsanfu** [Nhogs/popoto#85]
It's really a terrible project！
Not friendly for a newer.
When I nmp install ,How to continue?

**Comment by Popotojs** [comment]
The project is a bit old and not easy to integrate in recent frameworks but you have most details in project's [Wiki](https://github.com/Nhogs/popoto/wiki).
Once you npm install Popoto you have to create an Html page with your configuration, see [Getting-started](https://github.com/Nhogs/popoto/wiki/Getting-started) for details
You can also check examples in [popoto-examples](https://github.com/Nhogs/popoto-examples) project for real running configuration from npm install.

See this [simple-graph](https://github.com/Nhogs/popoto-examples/blob/master/simple-graph/index.html) config for script reference to Popoto in ```node_modules```.
