### ISSUE TITLE
How to give Custom CYPHER Queries?

### ISSUE THREAD

**Issue by Deepam-Rai** [Nhogs/popoto#92]
Can we provide custom CYPHER query and then build the graph visualization?  
Queries like:  
```
MATCH (p:Person)-[r:DIRECTED]->(m:Movie) RETURN p,r,m
```
And display the results in usual way how neo4j browser displays.

**Comment by evahaudi** [comment]
I would also want to know how one can use a customized cipher query, please respond.

**Comment by Popotojs** [comment]
Popoto is NOT a graph visualization library but a **visual query builder**.
The graph is equivalent to the “cypher” query and not a graph of the results.
The root node of the graph is the target of the search query and the graph is dynamic to add constraint to the query.
So only specific Cypher queries structures are supported.

That said, you can't provide a custom Cypher query but it is possible to start a graph using a **schema** with predefined constraints, see this example:
https://github.com/Nhogs/popoto-examples/tree/master/start-from-schema
You can look at the source code for details.

**Comment by Deepam-Rai** [comment]
Thank you, that was clarifying. Great work tho!

**Comment by darioamorosodaragona-tuni** [comment]
Can we have more details about how the schema works? 
I cannot find any information on the wiki. 
I defined my schema but I got an 'undefined' node.

**Comment by Popotojs** [comment]
You can have a look at [start-from-schema](https://github.com/Nhogs/popoto-examples/tree/master/start-from-schema) example the schema is defined like this:

``` javascript
    var schema = {
        label: "Person",
        rel: [
            {
                label: "ACTED_IN",
                target: {
                    label: "Movie",
                    value: {
                        title: "Jerry Maguire"
                    }
                }
            },
            {
                label: "ACTED_IN",
                target: {
                    label: "Movie",
                    value: {
                        title: "Top Gun"
                    }
                }
            }
        ]
    };
```

Or this [save](https://github.com/Nhogs/popoto-examples/tree/master/save) example:
This example contains 5 differents predefined [schema](https://github.com/Nhogs/popoto-examples/blob/6775320bf93bfcf85a84cb6e93d1f6323d86fc2e/save/index.html#L168) you can click on the left to start popoto with.
It also show how to [save a graph schema](https://github.com/Nhogs/popoto-examples/blob/master/save/index.html#L139) from current graph.

**Comment by darioamorosodaragona-tuni** [comment]
Yes, but for example is not specified anywhere that the property in the `value` field must be the first and the same property declared in the `provider.node.Provider` in `returnAttributes`.
